
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/martincazaban/Documents/FACULTAD/Programación Orientada a Objetos/PROYECTO INTEGRADOR/proyecto-poo/Servidor/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1450x717")
window.configure(bg = "#A4A4A4")


canvas = Canvas(
    window,
    bg = "#A4A4A4",
    height = 717,
    width = 1450,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    246.0,
    11.0,
    anchor="nw",
    text="Robot “Grupo Negro” - Servidor",
    fill="#FFFFFF",
    font=("InriaSans Regular", 64 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    131.0,
    185.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    164.0,
    199.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#9B9B9B",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=112.0,
    y=181.0,
    width=104.0,
    height=34.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=688.0,
    y=406.0,
    width=233.0,
    height=47.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    897.0,
    194.0,
    image=image_image_2
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    973.5,
    200.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#9B9B9B",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=953.0,
    y=184.0,
    width=41.0,
    height=30.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    597.0,
    194.0,
    image=image_image_3
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    668.5,
    210.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#9B9B9B",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=643.0,
    y=192.0,
    width=51.0,
    height=34.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=465.0,
    y=590.0,
    width=161.0,
    height=46.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=465.0,
    y=275.0,
    width=226.0,
    height=39.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1119.0,
    y=247.0,
    width=206.0,
    height=44.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=465.0,
    y=340.0,
    width=211.0,
    height=45.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=17.0,
    y=609.0,
    width=123.0,
    height=36.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=688.0,
    y=340.0,
    width=236.0,
    height=45.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=16.0,
    y=545.0,
    width=230.0,
    height=45.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=17.0,
    y=475.0,
    width=229.0,
    height=49.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=465.0,
    y=406.0,
    width=207.0,
    height=47.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=1119.0,
    y=193.0,
    width=200.0,
    height=36.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat"
)
button_12.place(
    x=702.0,
    y=275.0,
    width=281.0,
    height=39.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_13 clicked"),
    relief="flat"
)
button_13.place(
    x=1119.0,
    y=135.0,
    width=132.0,
    height=35.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    699.0,
    520.0,
    image=image_image_4
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    780.5,
    528.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#9B9B9B",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=662.0,
    y=510.0,
    width=237.0,
    height=34.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_14 clicked"),
    relief="flat"
)
button_14.place(
    x=16.0,
    y=252.0,
    width=100.0,
    height=38.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    205.0,
    386.0,
    image=image_image_5
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    199.0,
    413.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#9B9B9B",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=31.0,
    y=396.0,
    width=336.0,
    height=32.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    1203.0,
    509.0,
    image=image_image_6
)

canvas.create_rectangle(
    983.0,
    377.0,
    1424.0,
    681.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
